### PR TITLE
Add transfer eth unit tests, Harden eth transfer

### PR DESCRIPTION
**Pull request by H34D**
## Description

Fix ETH Transfer

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Checklist:

- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

### CODE REVIEW

**Review by aaitor — COMMENTED** [review]
I think we must bump to `v1.1.2` here

**Comment by H34D** [comment]
let me research further and talk to sami first

**Comment by mrsmkl** [comment]
It was changed from `transfer` because auditors complained about it https://github.com/nevermined-io/contracts/issues/77

I think the current method should work, not sure what the problem is though...

**Comment by mrsmkl** [comment]
The integration test probably won't work after #145 so let's merge that one first?

**Review by mrsmkl — APPROVED** [review]
LGTM, checked that there weren't many problems with #145

**Pull request merged**
